on:
  workflow_dispatch:
  schedule:
    # run every 4 hours
    - cron: '20 */4 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: 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
          SKIP_UPDATED: 1
